#!/usr/bin/env python3
"""Generate the thesis appendix tables from the configuration files.

    venv/bin/python tools/thesis/gen_appendix.py

Writes thesis/generated/:
    params_*.tex      the parameter tables of appendix A
    scenarios.tex     the scenario table of appendix B

The point is that the appendix cannot drift from the system: if a value in params.yaml changes,
re-running this script updates the thesis. Never edit the generated files by hand.
"""
import os

import yaml

WS = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
CONFIG = os.path.join(WS, "src", "robofetch_factory", "config")
OUT = os.path.join(WS, "thesis", "generated")

HEADER = ("% GENERATED by tools/thesis/gen_appendix.py from "
          "src/robofetch_factory/config/ - do not edit by hand.\n")

# Unit and explanation for each parameter, keyed by its path in params.yaml. Anything not listed
# is still printed, with the comment from the YAML file as its explanation.
UNITS = {
    "robot.mass_kg": r"\si{\kilo\gram}",
    "robot.battery.capacity_wh": r"\si{\watt\hour}",
    "robot.battery.reserve_percent": r"\si{\percent}",
    "robot.battery.charge_power_w": r"\si{\watt}",
    "robot.battery.initial_percent": r"\si{\percent}",
    "robot.energy.idle_power_w": r"\si{\watt}",
    "robot.energy.drive_wh_per_m": r"\si{\watt\hour\per\metre}",
    "robot.energy.load_wh_per_m_per_kg": r"\si{\watt\hour\per\metre\per\kilo\gram}",
    "robot.energy.temp_loss_per_c": r"per \si{\degreeCelsius}",
    "robot.energy.worn_extra_draw": "fraction",
    "robot.thermal.ambient_c": r"\si{\degreeCelsius}",
    "robot.thermal.heat_c_per_s": r"\si{\degreeCelsius\per\second}",
    "robot.thermal.cool_per_s": r"\si{\per\second}",
    "robot.thermal.payload_heat_per_kg": r"per \si{\kilo\gram}",
    "robot.thermal.dock_cooling_factor": "factor",
    "robot.thermal.warn_c": r"\si{\degreeCelsius}",
    "robot.thermal.max_c": r"\si{\degreeCelsius}",
    "robot.thermal.resume_c": r"\si{\degreeCelsius}",
    "robot.wear.condition_min_percent": r"\si{\percent}",
    "robot.wear.per_wh": r"\si{\percent\per\watt\hour}",
    "robot.wear.per_c_s_above_warn": r"\si{\percent\per\second}",
    "robot.wear.initial_percent": r"\si{\percent}",
    "robot.motion.speed_m_s": r"\si{\metre\per\second}",
    "robot.motion.drive_load": "0--1",
    "robot.motion.dwell_load": "0--1",
    "robot.handling.max_payload_kg": r"\si{\kilo\gram}",
    "robot.handling.load_time_s": r"\si{\second}",
    "robot.handling.unload_time_s": r"\si{\second}",
    "time.shift_duration_s": r"\si{\second}",
    "time.time_scale": "factor",
    "time.seed": "---",
}


def escape(text):
    out = str(text)
    for a, b in (("_", r"\_"), ("%", r"\%"), ("&", r"\&"), ("#", r"\#")):
        out = out.replace(a, b)
    return out


def fmt(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        return f"{value:g}"
    if isinstance(value, list):
        return ", ".join(fmt(v) for v in value)
    return escape(value)


def flatten(node, prefix=""):
    for key, value in node.items():
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            yield from flatten(value, path)
        else:
            yield path, value


def table(rows, caption, label, col="Parameter & Value & Unit"):
    # The faculty style sets double spacing for the running text; tables are unreadable in it.
    lines = [HEADER, r"\begin{table}[H]", r"    \centering", r"    \begin{spacing}{1.0}",
             f"    \\caption{{{caption}}}", f"    \\label{{{label}}}",
             r"    \small", r"    \begin{tabular}{lrl}", r"        \toprule",
             f"        {col}\\\\", r"        \midrule"]
    for name, value, unit in rows:
        lines.append(f"        \\texttt{{{escape(name)}}} & {fmt(value)} & {unit}\\\\")
    lines += [r"        \bottomrule", r"    \end{tabular}", r"    \end{spacing}",
              r"\end{table}", ""]
    return "\n".join(lines)


def params_tables(params):
    groups = [
        ("robot", "Robot platform, battery, energy, heat and wear",
         "tab:params-robot", ("robot.",)),
        ("mission", "Mission: navigation, objective and the fast simulator",
         "tab:params-mission", ("mission.navigation.", "mission.objective.",
                                "mission.simulation.")),
        ("models", "Decision models: neuro-symbolic layer, its training, and PPO",
         "tab:params-models", ("mission.neurosymbolic.", "mission.rl.")),
        ("evaluation", "Evaluation protocol and the simulated clock",
         "tab:params-eval", ("mission.evaluation.", "time.")),
    ]
    written = []
    for name, caption, label, prefixes in groups:
        rows = [(path, value, UNITS.get(path, ""))
                for path, value in flatten(params)
                if any(path.startswith(p) for p in prefixes)]
        path = os.path.join(OUT, f"params_{name}.tex")
        with open(path, "w") as fh:
            fh.write(table(rows, caption, label))
        written.append(path)
    return written


def sections_table(params):
    sections = params["factory"]["sections"]
    defaults = params["factory"]["section_defaults"]
    rows = []
    for sid, sec in sections.items():
        for key, value in sec.items():
            rows.append((f"{sid}.{key}", value, ""))
    for key, value in defaults.items():
        rows.append((f"defaults.{key}", value, ""))
    path = os.path.join(OUT, "params_factory.tex")
    with open(path, "w") as fh:
        fh.write(table(rows, "The three production sections and the defaults every section "
                             "inherits unless it overrides them", "tab:params-factory"))
    return path


def scenarios_table(training):
    rows = []
    for name in sorted(os.listdir(os.path.join(CONFIG, "scenarios"))):
        if not name.endswith(".yaml"):
            continue
        with open(os.path.join(CONFIG, "scenarios", name)) as fh:
            cfg = yaml.safe_load(fh)
        key = name[:-5]
        overrides = [f"{p} = {fmt(v)}" for p, v in flatten(cfg)
                     if p not in ("name", "description")]
        rows.append((key, "seen" if key in training else "unseen",
                     cfg.get("description", ""), overrides))
    lines = [HEADER, r"\begin{spacing}{1.0}", r"\small",
             r"\begin{longtable}{>{\raggedright\arraybackslash}p{3.25cm}"
             r">{\raggedright\arraybackslash}p{1.1cm}"
             r">{\raggedright\arraybackslash}p{7.45cm}}",
             r"    \caption{The twelve scenarios: what each one changes and what it stresses. "
             r"``Seen'' scenarios are available for training, ``unseen'' ones were written "
             r"afterwards and are used only for evaluation. The exact parameter overrides are in "
             r"the scenario files of the repository.}\label{tab:scenarios-full}\\",
             r"    \toprule",
             r"    Scenario & Split & Description and parameter overrides\\",
             r"    \midrule", r"    \endfirsthead",
             r"    \toprule",
             r"    Scenario & Split & Description and parameter overrides\\",
             r"    \midrule", r"    \endhead"]
    for key, split, description, overrides in rows:
        detail = escape(description)
        lines.append(f"    \\texttt{{{escape(key)}}} & {split} & {detail}\\\\[2pt]")
    lines += [r"    \bottomrule", r"\end{longtable}", r"\end{spacing}", ""]
    path = os.path.join(OUT, "scenarios.tex")
    with open(path, "w") as fh:
        fh.write("\n".join(lines))
    return path


def main():
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(CONFIG, "params.yaml")) as fh:
        params = yaml.safe_load(fh)
    written = params_tables(params)
    written.append(sections_table(params))
    written.append(scenarios_table(set(params["mission"]["evaluation"]["training_scenarios"])))
    for path in written:
        print(os.path.relpath(path, WS))


if __name__ == "__main__":
    main()
